server:
  port: 9000

spring:
  application:
    name: spring-cloud-zuul-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
  instance:
    hostname: spring-cloud-zuul-9000
zuul:
  routes:
    spring-cloud-caller-service: /cloud-c/**
  host:
    connect-timeout-millis: 15000 #HTTP连接超时大于Hystrix的超时时间
    socket-timeout-millis: 60000   #socket超时
ribbon:  #设置ribbon的超时时间小于zuul的超时时间
  ReadTimeout: 10000
  ConnectTimeout: 10000
