server:
  port: 9000

spring:
  application:
    name: spring-cloud-zuul-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
  instance:
    hostname: spring-cloud-zuul-9000
zuul:
  routes:
    spring-cloud-caller-service: /cloud-c/**
